Traceback (most recent call last):
  File "/mnt/software/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/mnt/software/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/mnt/software/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/mnt/software/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/mnt/software/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/software/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/mnt/software/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/mnt/software/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
2/(wacc(E=100,D=30,rE=.08,rD=.04,tC=.35) - 0.01) # $2M in FCF, growing at 1%/year
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-0cbe3844b6b4>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;36m2[0m[0;34m/[0m[0;34m([0m[0mwacc[0m[0;34m([0m[0mE[0m[0;34m=[0m[0;36m100[0m[0;34m,[0m[0mD[0m[0;34m=[0m[0;36m30[0m[0;34m,[0m[0mrE[0m[0;34m=[0m[0;36m.08[0m[0;34m,[0m[0mrD[0m[0;34m=[0m[0;36m.04[0m[0;34m,[0m[0mtC[0m[0;34m=[0m[0;36m.35[0m[0;34m)[0m [0;34m-[0m [0;36m0.01[0m[0;34m)[0m [0;31m# $2M in FCF, growing at 1%/year[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mTypeError[0m: unsupported operand type(s) for -: 'tuple' and 'float'
TypeError: unsupported operand type(s) for -: 'tuple' and 'float'

